export const eventsData = [
  {
    title: 'Keynote Sessions',
    slug: 'keynote-sessions',
    date: 'March 27, 2025',
    time: '9:00 AM - 12:00 PM',
    description: 'Hear from world-renowned speakers sharing visionary insights and transformative ideas that will shape the future of our industry.',
    detailedDescription: 'Our keynote sessions feature distinguished speakers from around the world who will share their expertise and vision for the future. These sessions are designed to inspire, challenge, and provide actionable insights that you can apply in your professional journey. Each keynote will be followed by a Q&A session, allowing you to engage directly with the speakers.',
    icon: '🎤',
    color: 'from-primary to-primary-dark',
  },
  {
    title: 'Planery Sessions',
    slug: 'planery-sessions',
    date: 'March 27-28, 2025',
    time: '2:00 PM - 5:00 PM',
    description: 'Hands-on workshops led by experts covering the latest tools, technologies, and methodologies in interactive sessions.',
    detailedDescription: 'Join our interactive plenary sessions where industry experts will guide you through the latest tools, technologies, and methodologies. These sessions combine theoretical knowledge with practical applications, ensuring you leave with skills you can immediately implement. Perfect for both beginners and experienced professionals looking to expand their expertise.',
    icon: '💻',
    color: 'from-primary-dark to-primary',
  },
  {
    title: 'Panel Discussions',
    slug: 'panel-discussions',
    date: 'March 28, 2025',
    time: '10:00 AM - 1:00 PM',
    description: 'Engage in thought-provoking discussions with industry leaders exploring current challenges and future opportunities.',
    detailedDescription: 'Our panel discussions bring together diverse perspectives from industry leaders, academics, and innovators. These moderated sessions explore current challenges, emerging trends, and future opportunities in the field. Attendees are encouraged to participate in the discussion, ask questions, and share their own insights and experiences.',
    icon: '👥',
    color: 'from-primary to-primary-dark',
  },
  {
    title: 'Insightful Workshops',
    slug: 'insightful-workshops',
    date: 'March 27-29, 2025',
    time: '5:30 PM - 7:30 PM',
    description: 'Connect with peers, potential collaborators, and mentors in structured networking events designed to foster meaningful relationships.',
    detailedDescription: 'These specialized workshops provide deep dives into specific topics and skills. Led by experienced practitioners, these sessions are hands-on and interactive, allowing you to learn by doing. Topics range from technical skills to soft skills development, ensuring there\'s something valuable for everyone. Build your network while building your skills.',
    icon: '🤝',
    color: 'from-primary-dark to-primary',
  },
  {
    title: 'Research Presentations',
    slug: 'research-presentations',
    date: 'March 28-29, 2025',
    time: '9:00 AM - 5:00 PM',
    description: 'Discover groundbreaking research from leading academics and practitioners presenting their latest findings and innovations.',
    detailedDescription: 'Explore cutting-edge research from leading academics and practitioners in the field. These presentations showcase the latest findings, innovative methodologies, and breakthrough discoveries. Whether you\'re a researcher yourself or simply curious about the latest developments, these sessions offer valuable insights into the future direction of the industry.',
    icon: '📊',
    color: 'from-primary to-primary-dark',
  },
  {
    title: 'Awards Ceremony',
    slug: 'awards-ceremony',
    date: 'March 29, 2025',
    time: '6:00 PM - 8:00 PM',
    description: 'Celebrate excellence and innovation as we honor outstanding contributions and achievements in our field.',
    detailedDescription: 'Join us for an elegant evening celebration honoring outstanding contributions and achievements in our field. The awards ceremony recognizes individuals and organizations that have made significant impacts through their work, innovation, and dedication. This is also a wonderful networking opportunity in a more relaxed, celebratory atmosphere.',
    icon: '🏆',
    color: 'from-primary-dark to-primary',
  },
];