export const speakersData = [
  {
    name: 'Dr. Sarah Mitchell',
    slug: 'sarah-mitchell',
    title: 'Chief Innovation Officer',
    organization: 'TechVision Global',
    expertise: 'Artificial Intelligence & Machine Learning',
    image: '/images/speakers/sarah-mitchell.jpg', // You'll need to add actual images
    bio: 'Dr. Sarah Mitchell is a pioneering force in artificial intelligence and machine learning with over 15 years of experience driving innovation in the tech industry.',
    longBio: 'Dr. Sarah Mitchell is a world-renowned expert in artificial intelligence and machine learning, currently serving as Chief Innovation Officer at TechVision Global. With a Ph.D. in Computer Science from MIT, she has published over 50 research papers and holds 12 patents in AI technologies. Her work focuses on ethical AI development and practical applications of machine learning in enterprise environments. She has been recognized as one of the top 100 most influential people in AI by Tech Magazine and regularly keynotes at international conferences.',
    achievements: [
      'Published 50+ research papers in AI and ML',
      'Holds 12 patents in AI technologies',
      'Named Top 100 Most Influential in AI by Tech Magazine',
      'Led AI transformation initiatives for Fortune 500 companies',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/sarahmitchell',
      twitter: 'https://twitter.com/sarahmitchell',
      website: 'https://sarahmitchell.com',
    },
    sessionTitle: 'The Future of AI: Ethics and Innovation',
    sessionTime: 'March 27, 2025 - 9:00 AM',
  },
  {
    name: 'Prof. James Chen',
    slug: 'james-chen',
    title: 'Professor of Computer Science',
    organization: 'Stanford University',
    expertise: 'Quantum Computing & Cryptography',
    image: '/images/speakers/james-chen.jpg',
    bio: 'Professor James Chen is a leading researcher in quantum computing and cryptography, shaping the future of secure communications.',
    longBio: 'Professor James Chen is a distinguished academic and researcher at Stanford University, specializing in quantum computing and cryptography. With over 20 years of teaching and research experience, he has mentored hundreds of students and contributed groundbreaking research to the field of quantum algorithms. His work on quantum-resistant cryptography has been adopted by several government agencies and tech companies. He serves on multiple advisory boards and is a frequent consultant for leading technology firms.',
    achievements: [
      'Developed quantum-resistant cryptography algorithms',
      'Author of "Quantum Computing: A Practical Approach"',
      'Recipient of the Turing Award for Computing Excellence',
      'Advisor to government agencies on cybersecurity',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/jameschen',
      twitter: 'https://twitter.com/profchen',
      website: 'https://jameschen.stanford.edu',
    },
    sessionTitle: 'Quantum Computing: The Next Frontier',
    sessionTime: 'March 27, 2025 - 2:00 PM',
  },
  {
    name: 'Maria Rodriguez',
    slug: 'maria-rodriguez',
    title: 'Founder & CEO',
    organization: 'InnovateX Solutions',
    expertise: 'Digital Transformation & Leadership',
    image: '/images/speakers/maria-rodriguez.jpg',
    bio: 'Maria Rodriguez is an entrepreneur and thought leader who has successfully led digital transformation initiatives across multiple industries.',
    longBio: 'Maria Rodriguez is the Founder and CEO of InnovateX Solutions, a leading consultancy specializing in digital transformation. She has over 18 years of experience helping organizations navigate technological change and build innovative business models. Under her leadership, InnovateX has grown to serve clients in 30+ countries. Maria is a passionate advocate for diversity in tech and regularly mentors young entrepreneurs. She has been featured in Forbes, Fortune, and Entrepreneur Magazine.',
    achievements: [
      'Built InnovateX Solutions to serve 30+ countries',
      'Featured speaker at World Economic Forum',
      'Named "Top 50 Women in Tech" by Fortune Magazine',
      'Mentored 100+ startups through accelerator programs',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/mariarodriguez',
      twitter: 'https://twitter.com/maria_innovates',
      website: 'https://innovatexsolutions.com',
    },
    sessionTitle: 'Leading Digital Transformation in Modern Organizations',
    sessionTime: 'March 28, 2025 - 10:00 AM',
  },
  {
    name: 'Dr. Akira Tanaka',
    slug: 'akira-tanaka',
    title: 'Director of Research',
    organization: 'Global Robotics Institute',
    expertise: 'Robotics & Automation',
    image: '/images/speakers/akira-tanaka.jpg',
    bio: 'Dr. Akira Tanaka is a robotics pioneer whose innovations are transforming manufacturing and healthcare industries worldwide.',
    longBio: 'Dr. Akira Tanaka serves as the Director of Research at the Global Robotics Institute, where he leads a team of 50+ researchers working on cutting-edge robotics and automation technologies. His work spans from industrial robotics to medical applications, with several of his inventions now being used in hospitals and factories worldwide. He holds a Ph.D. in Mechanical Engineering from the University of Tokyo and has received numerous international awards for his contributions to robotics.',
    achievements: [
      'Developed surgical robots used in 200+ hospitals worldwide',
      'Holds 25+ patents in robotics and automation',
      'Winner of the IEEE Robotics and Automation Award',
      'Published 80+ peer-reviewed research papers',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/akiratanaka',
      twitter: 'https://twitter.com/dr_tanaka_robotics',
      website: 'https://globalrobotics.org/tanaka',
    },
    sessionTitle: 'Robotics Revolution: From Factory Floor to Operating Room',
    sessionTime: 'March 28, 2025 - 5:30 PM',
  },
  {
    name: 'Emma Williams',
    slug: 'emma-williams',
    title: 'Head of Sustainability',
    organization: 'GreenTech Innovations',
    expertise: 'Sustainable Technology & Climate Tech',
    image: '/images/speakers/emma-williams.jpg',
    bio: 'Emma Williams is leading the charge in sustainable technology, helping companies reduce their carbon footprint through innovative solutions.',
    longBio: 'Emma Williams is the Head of Sustainability at GreenTech Innovations, where she oversees initiatives that have helped reduce carbon emissions by over 10 million tons annually. With a background in environmental engineering and business strategy, she bridges the gap between sustainability goals and practical implementation. Emma has advised governments and corporations on climate action strategies and is a regular contributor to leading environmental publications. Her TED talk on sustainable innovation has been viewed over 5 million times.',
    achievements: [
      'Reduced carbon emissions by 10M+ tons through tech initiatives',
      'Advisor to UN Climate Action Summit',
      'TED talk with 5M+ views on sustainable innovation',
      'Author of "Green Code: Programming for a Sustainable Future"',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/emmawilliams',
      twitter: 'https://twitter.com/emma_greentech',
      website: 'https://greentech-innovations.com',
    },
    sessionTitle: 'Technology for a Sustainable Future',
    sessionTime: 'March 29, 2025 - 9:00 AM',
  },
  {
    name: 'Dr. Raj Patel',
    slug: 'raj-patel',
    title: 'VP of Engineering',
    organization: 'CloudScale Systems',
    expertise: 'Cloud Architecture & DevOps',
    image: '/images/speakers/raj-patel.jpg',
    bio: 'Dr. Raj Patel is a cloud architecture expert who has designed systems serving billions of users across the globe.',
    longBio: 'Dr. Raj Patel is the Vice President of Engineering at CloudScale Systems, where he leads the architecture of cloud platforms serving over 2 billion users globally. With expertise spanning cloud computing, distributed systems, and DevOps practices, he has been instrumental in building some of the most scalable systems in the industry. Before CloudScale, he held senior positions at major tech companies and contributed to the development of several open-source projects. He frequently speaks at technical conferences and contributes to cloud computing standards.',
    achievements: [
      'Architected systems serving 2B+ users globally',
      'Contributor to major open-source cloud projects',
      'Author of "Scalable Cloud Architecture Patterns"',
      'Led cloud migration for 100+ enterprise clients',
    ],
    socialLinks: {
      linkedin: 'https://linkedin.com/in/rajpatel',
      twitter: 'https://twitter.com/raj_cloudscale',
      website: 'https://rajpatel.dev',
    },
    sessionTitle: 'Building Scalable Cloud Systems for the Next Billion Users',
    sessionTime: 'March 29, 2025 - 2:00 PM',
  },
];